version: "3"

services:
  php:
    container_name: "${nome_projeto}-CertBot-PHP"
    build:
      context: ./bin/php
    expose:
      - 80
      - 443
    links:
     - banco
    volumes:
      - ./www:/var/www/html
    environment:
      LETSENCRYPT_HOST: docs.sgpo.online
      LETSENCRYPT_EMAIL: danieldelimamazali@hotmail.com
      VIRTUAL_HOST: docs.sgpo.online
      

networks:
  default:
    external:
      name: nginx-proxy
